### ISSUE TITLE
RuntimeError: 3 : this is not a parametric design

### ISSUE THREAD

**Issue by danieldean1** [DVE2000/Dogbone#64]
Failed:
Traceback (most recent call last):
  File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/dbutils.py", line 174, in notify
    notify_method(args)
  File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 651, in onExecute
    self.createStaticDogbones()
  File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 969, in createStaticDogbones
    startTlMarker = self.design.timeline.markerPosition
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldean/Library/Application Support/Autodesk/webdeploy/production/6997599ab67b7e881f25c2311930a09bc5ac662f/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/fusion.py", line 68034, in _get_timeline
    return _fusion.Design__get_timeline(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : this is not a parametric design

----------
I don't have the parametric mode selected.

RUNNING: Fusion 2.0.19440 x86_64 [Native] 

Not super familiar with python or addIn tbh, would love to use this addin though!

<img width="1053" alt="Screenshot 2024-07-05 at 6 45 19 PM" src="https://github.com/DVE2000/Dogbone/assets/9410800/66f71884-ba8f-46d0-a7f8-e906e65ad77e">

**Comment by pludikar** [comment]
Hi Daniel,

This error should have been caught and should have displayed a dialogue which asks if you’d like to change to parametric mode. I've checked to see if I didn’t break it with changes I made in the last 2 or 3 years, it looks ok. However, I noticed that if you attempt to install/run the addin while in non-parametric mode, it will fail to load.  I'll work on that to fix it - it's very unlikely to happen more than once.  After it's loaded successfully and you click on the "load on Startup" checkbox, you shouldn't experience the issue again.

"Parametric" means having the F360 capture design history turned on. My addin will only work when history is active. If you don’t have a timeline with forward, back, start, end and play buttons at the bottom of the f360 page, then you aren’t in parametric mode.  If you see the dogbone icons in the main menu tab ribbon while not capturing design history, you can click on the dogbone button and a dialog box will pop up - clicking "YES" is all you need to do.

Alternatively right click on the top root of the document browser you are using - at the bottom of the popped up menu you'll see  "Capture Design History" - click that and you should be all set.

Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: danieldean1 ***@***.***>
Sent: Friday, July 5, 2024 6:47:12 PM
To: DVE2000/Dogbone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DVE2000/Dogbone] RuntimeError: 3 : this is not a parametric design (Issue #64)


Failed:
Traceback (most recent call last):
File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/dbutils.py", line 174, in notify
notify_method(args)
File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 651, in onExecute
self.createStaticDogbones()
File "/Users/danieldean/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 969, in createStaticDogbones
startTlMarker = self.design.timeline.markerPosition
^^^^^^^^^^^^^^^^^^^^
File "/Users/danieldean/Library/Application Support/Autodesk/webdeploy/production/6997599ab67b7e881f25c2311930a09bc5ac662f/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/fusion.py", line 68034, in _get_timeline
return _fusion.Design__get_timeline(self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : this is not a parametric design

________________________________

I don't have the parametric mode selected.

RUNNING: Fusion 2.0.19440 x86_64 [Native]

Not super familiar with python or addIn tbh, would love to use this addin though!

Screenshot.2024-07-05.at.6.45.19.PM.png (view on web)<https://github.com/DVE2000/Dogbone/assets/9410800/66f71884-ba8f-46d0-a7f8-e906e65ad77e>

**Comment by pludikar** [comment]
Hi Daniel,
I've added an additional check to make sure the add-in is loaded while in parameter mode.  I've upped the version to 2.2.2 - download that and reinstall.  If you still have issues let me know.

Peter
